#!/bin/bash
MT="mtn"
sources=`$MT list known . --depth=0 | grep '.xml$'`

for i in $sources; do
(
  file=`basename $i`
  htmlfile=`echo $file | sed s/xml/html/`
  pdffile=`echo $file | sed s/xml/pdf/`
  txtfile=`echo $file | sed s/xml/txt/`
  title=`xsltproc --novalid _rfctitle.xslt $file`

  rfcnr=${file:3:4}
  echo "<t>
          RFC-$rfcnr : $title
          <eref target=\"http://www.xaraya.com/documentation/rfcs/$pdffile\">[PDF]</eref>
          <eref target=\"http://www.xaraya.com/documentation/rfcs/$htmlfile\">[HTML]</eref>
          <eref target=\"http://www.xaraya.com/documentation/rfcs/$txtfile\">[TXT]</eref>
       </t>"
) 
done
