#!/bin/bash

sources=`mt list known . --depth=0 | grep '.xml$'`

for i in $sources; do
(
  file=`basename $i`
  htmlfile=`echo $file | sed s/xml/html/`
  title=`xsltproc --novalid _rfctitle.xslt $file`

  rfcnr=${file:3:4}
  echo "<t><eref target=\"http://www.xaraya.com/documentation/rfcs/$htmlfile\">RFC-$rfcnr : $title</eref></t>"
) 
done
