#!/bin/sh

sources=`bk sfiles -g | grep ".xml"`


for i in $sources; do
(
  htmlfile=`echo $i | sed s/xml/html/`
  title=$i
  echo "<t>"
  echo "<eref target=\"http://docs.xaraya.com/docs/rfcs/$htmlfile\">$title</eref>"
  echo "</t>"
) 
done